// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzFCUVjinnS7DYVvnAXfZE4IHIvYFvZyE',
    appId: '1:230365101088:web:1ce1918587b1fc67055045',
    messagingSenderId: '230365101088',
    projectId: 'newmandala525-baed3',
    authDomain: 'newmandala525-baed3.firebaseapp.com',
    storageBucket: 'newmandala525-baed3.firebasestorage.app',
    measurementId: 'G-LMT9V986BC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzGP7MNhAcYTxFbB-pXadWjsCbBhMh_Mc',
    appId: '1:230365101088:android:99876b0fa0505f76055045',
    messagingSenderId: '230365101088',
    projectId: 'newmandala525-baed3',
    storageBucket: 'newmandala525-baed3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRpQK4N4srhAnVrgZUBMYSctMOxn4p0fg',
    appId: '1:230365101088:ios:fe5779ef5c877140055045',
    messagingSenderId: '230365101088',
    projectId: 'newmandala525-baed3',
    storageBucket: 'newmandala525-baed3.firebasestorage.app',
    iosBundleId: 'com.example.mandala525',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRpQK4N4srhAnVrgZUBMYSctMOxn4p0fg',
    appId: '1:230365101088:ios:fe5779ef5c877140055045',
    messagingSenderId: '230365101088',
    projectId: 'newmandala525-baed3',
    storageBucket: 'newmandala525-baed3.firebasestorage.app',
    iosBundleId: 'com.example.mandala525',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzFCUVjinnS7DYVvnAXfZE4IHIvYFvZyE',
    appId: '1:230365101088:web:bc9dc30d3b5b35ab055045',
    messagingSenderId: '230365101088',
    projectId: 'newmandala525-baed3',
    authDomain: 'newmandala525-baed3.firebaseapp.com',
    storageBucket: 'newmandala525-baed3.firebasestorage.app',
    measurementId: 'G-DZ3GMWVYDX',
  );
}
